var LanguageList = [
    {"id":"ab","text":"Abkhaz"},
    {"id":"aa","text":"Afar"},
    {"id":"af","text":"Afrikaans"},
    {"id":"ak","text":"Akan"},
    {"id":"sq","text":"Albanian"},
    {"id":"am","text":"Amharic"},
    {"id":"ar","text":"Arabic"},
    {"id":"an","text":"Aragonese"},
    {"id":"hy","text":"Armenian"},
    {"id":"as","text":"Assamese"},
    {"id":"av","text":"Avaric"},
    {"id":"ae","text":"Avestan"},
    {"id":"ay","text":"Aymara"},
    {"id":"az","text":"Azerbaijani"},
    {"id":"bm","text":"Bambara"},
    {"id":"ba","text":"Bashkir"},
    {"id":"eu","text":"Basque"},
    {"id":"be","text":"Belarusian"},
    {"id":"bn","text":"Bengali"},
    {"id":"bh","text":"Bihari"},
    {"id":"bi","text":"Bislama"},
    {"id":"bs","text":"Bosnian"},
    {"id":"br","text":"Breton"},
    {"id":"bg","text":"Bulgarian"},
    {"id":"my","text":"Burmese"},
    {"id":"ca","text":"Catalan; Valencian"},
    {"id":"ch","text":"Chamorro"},
    {"id":"ce","text":"Chechen"},
    {"id":"ny","text":"Chichewa; Chewa; Nyanja"},
    {"id":"zh","text":"Chinese"},
    {"id":"cv","text":"Chuvash"},
    {"id":"kw","text":"Cornish"},
    {"id":"co","text":"Corsican"},
    {"id":"cr","text":"Cree"},
    {"id":"hr","text":"Croatian"},
    {"id":"cs","text":"Czech"},
    {"id":"da","text":"Danish"},
    {"id":"dv","text":"Divehi; Dhivehi; Maldivian;"},
    {"id":"nl","text":"Dutch"},
    {"id":"en","text":"English"},
    {"id":"eo","text":"Esperanto"},
    {"id":"et","text":"Estonian"},
    {"id":"ee","text":"Ewe"},
    {"id":"fo","text":"Faroese"},
    {"id":"fj","text":"Fijian"},
    {"id":"fi","text":"Finnish"},
    {"id":"fr","text":"French"},
    {"id":"ff","text":"Fula; Fulah; Pulaar; Pular"},
    {"id":"gl","text":"Galician"},
    {"id":"ka","text":"Georgian"},
    {"id":"de","text":"German"},
    {"id":"el","text":"Greek, Modern"},
    {"id":"gn","text":"Guaraní"},
    {"id":"gu","text":"Gujarati"},
    {"id":"ht","text":"Haitian; Haitian Creole"},
    {"id":"ha","text":"Hausa"},
    {"id":"he","text":"Hebrew (modern)"},
    {"id":"hz","text":"Herero"},
    {"id":"hi","text":"Hindi"},
    {"id":"ho","text":"Hiri Motu"},
    {"id":"hu","text":"Hungarian"},
    {"id":"ia","text":"Interlingua"},
    {"id":"id","text":"Indonesian"},
    {"id":"ie","text":"Interlingue"},
    {"id":"ga","text":"Irish"},
    {"id":"ig","text":"Igbo"},
    {"id":"ik","text":"Inupiaq"},
    {"id":"io","text":"Ido"},
    {"id":"is","text":"Icelandic"},
    {"id":"it","text":"Italian"},
    {"id":"iu","text":"Inuktitut"},
    {"id":"ja","text":"Japanese"},
    {"id":"jv","text":"Javanese"},
    {"id":"kl","text":"Kalaallisut, Greenlandic"},
    {"id":"kn","text":"Kannada"},
    {"id":"kr","text":"Kanuri"},
    {"id":"ks","text":"Kashmiri"},
    {"id":"kk","text":"Kazakh"},
    {"id":"km","text":"Khmer"},
    {"id":"ki","text":"Kikuyu, Gikuyu"},
    {"id":"rw","text":"Kinyarwanda"},
    {"id":"ky","text":"Kirghiz, Kyrgyz"},
    {"id":"kv","text":"Komi"},
    {"id":"kg","text":"Kongo"},
    {"id":"ko","text":"Korean"},
    {"id":"ku","text":"Kurdish"},
    {"id":"kj","text":"Kwanyama, Kuanyama"},
    {"id":"la","text":"Latin"},
    {"id":"lb","text":"Luxembourgish, Letzeburgesch"},
    {"id":"lg","text":"Luganda"},
    {"id":"li","text":"Limburgish, Limburgan, Limburger"},
    {"id":"ln","text":"Lingala"},
    {"id":"lo","text":"Lao"},
    {"id":"lt","text":"Lithuanian"},
    {"id":"lu","text":"Luba-Katanga"},
    {"id":"lv","text":"Latvian"},
    {"id":"gv","text":"Manx"},
    {"id":"mk","text":"Macedonian"},
    {"id":"mg","text":"Malagasy"},
    {"id":"ms","text":"Malay"},
    {"id":"ml","text":"Malayalam"},
    {"id":"mt","text":"Maltese"},
    {"id":"mi","text":"Māori"},
    {"id":"mr","text":"Marathi (Marāṭhī)"},
    {"id":"mh","text":"Marshallese"},
    {"id":"mn","text":"Mongolian"},
    {"id":"na","text":"Nauru"},
    {"id":"nv","text":"Navajo, Navaho"},
    {"id":"nb","text":"Norwegian Bokmål"},
    {"id":"nd","text":"North Ndebele"},
    {"id":"ne","text":"Nepali"},
    {"id":"ng","text":"Ndonga"},
    {"id":"nn","text":"Norwegian Nynorsk"},
    {"id":"no","text":"Norwegian"},
    {"id":"ii","text":"Nuosu"},
    {"id":"nr","text":"South Ndebele"},
    {"id":"oc","text":"Occitan"},
    {"id":"oj","text":"Ojibwe, Ojibwa"},
    {"id":"cu","text":"Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic"},
    {"id":"om","text":"Oromo"},
    {"id":"or","text":"Oriya"},
    {"id":"os","text":"Ossetian, Ossetic"},
    {"id":"pa","text":"Panjabi, Punjabi"},
    {"id":"pi","text":"Pāli"},
    {"id":"fa","text":"Persian"},
    {"id":"pl","text":"Polish"},
    {"id":"ps","text":"Pashto, Pushto"},
    {"id":"pt","text":"Portuguese"},
    {"id":"qu","text":"Quechua"},
    {"id":"rm","text":"Romansh"},
    {"id":"rn","text":"Kirundi"},
    {"id":"ro","text":"Romanian, Moldavian, Moldovan"},
    {"id":"ru","text":"Russian"},
    {"id":"sa","text":"Sanskrit (Saṁskṛta)"},
    {"id":"sc","text":"Sardinian"},
    {"id":"sd","text":"Sindhi"},
    {"id":"se","text":"Northern Sami"},
    {"id":"sm","text":"Samoan"},
    {"id":"sg","text":"Sango"},
    {"id":"sr","text":"Serbian"},
    {"id":"gd","text":"Scottish Gaelic; Gaelic"},
    {"id":"sn","text":"Shona"},
    {"id":"si","text":"Sinhala, Sinhalese"},
    {"id":"sk","text":"Slovak"},
    {"id":"sl","text":"Slovene"},
    {"id":"so","text":"Somali"},
    {"id":"st","text":"Southern Sotho"},
    {"id":"es","text":"Spanish; Castilian"},
    {"id":"su","text":"Sundanese"},
    {"id":"sw","text":"Swahili"},
    {"id":"ss","text":"Swati"},
    {"id":"sv","text":"Swedish"},
    {"id":"ta","text":"Tamil"},
    {"id":"te","text":"Telugu"},
    {"id":"tg","text":"Tajik"},
    {"id":"th","text":"Thai"},
    {"id":"ti","text":"Tigrinya"},
    {"id":"bo","text":"Tibetan Standard, Tibetan, Central"},
    {"id":"tk","text":"Turkmen"},
    {"id":"tl","text":"Tagalog"},
    {"id":"tn","text":"Tswana"},
    {"id":"to","text":"Tonga (Tonga Islands)"},
    {"id":"tr","text":"Turkish"},
    {"id":"ts","text":"Tsonga"},
    {"id":"tt","text":"Tatar"},
    {"id":"tw","text":"Twi"},
    {"id":"ty","text":"Tahitian"},
    {"id":"ug","text":"Uighur, Uyghur"},
    {"id":"uk","text":"Ukrainian"},
    {"id":"ur","text":"Urdu"},
    {"id":"uz","text":"Uzbek"},
    {"id":"ve","text":"Venda"},
    {"id":"vi","text":"Vietnamese"},
    {"id":"vo","text":"Volapük"},
    {"id":"wa","text":"Walloon"},
    {"id":"cy","text":"Welsh"},
    {"id":"wo","text":"Wolof"},
    {"id":"fy","text":"Western Frisian"},
    {"id":"xh","text":"Xhosa"},
    {"id":"yi","text":"Yiddish"},
    {"id":"yo","text":"Yoruba"},
    {"id":"za","text":"Zhuang, Chuang"}
  ];

//create custom editor
var select2LanguageEditor = function (cell, onRendered, success, cancel, editorParams) {

    //create input element to hold select
    var editor = document.createElement("select");
    editor.className = "form-control";
    editor.style.width = "100%";
    editor.style.height = "100%";
    onRendered(function () {
        var select_2 = $(editor);

        select_2.select2({
            placeholder: 'Select',
            data: LanguageList,
            width: 300,
            minimumInputLength: 0,
            theme: 'bootstrap4'
        });

        select_2.on('change', function (e) {
            success(select_2.val());
        });


        select_2.on('blur', function (e) {
            cancel();
        });
    });
    //add editor to cell
    return editor;
}